import {LoginComponent} from "./security/login/login.component";
import {LogoutComponent} from "./security/logout/LogoutComponent";
import {RouterModule, Routes} from "@angular/router";
import {NgModule} from "@angular/core";
import {AuthGuard} from "./security/auth.guard";
import {ReportScreenTributacaoComponent} from "./screen-reports/report-screen-tributacao/report-screen-tributacao.component";
import {ReportScreenAdministracaoComponent} from "./screen-reports/report-screen-administracao/report-screen-administracao.component";
import {ReportScreenFinanceiroComponent} from "./screen-reports/report-screen-financeiro/report-screen-financeiro.component";
import {ReportScreenAuxiliarComponent} from "./screen-reports/report-screen-auxiliar/report-screen-auxiliar.component";
import {ReportScreenProcuradoriaComponent} from "./screen-reports/report-screen-procuradoria/report-screen-procuradoria.component";
import {ReportScreenUrbanismoComponent} from "./screen-reports/report-screen-urbanismo/report-screen-urbanismo.component";
import {ReportScreenNotafiscalComponent} from "./screen-reports/report-screen-notafiscal/report-screen-notafiscal.component";
import {ReportScreenEconomicoComponent} from "./screen-reports/report-screen-economico/report-screen-economico.component";
import {ReportScreenTransporteComponent} from "./screen-reports/report-screen-transporte/report-screen-transporte.component";

const routes: Routes = [
  {path: '', redirectTo: '/sample', pathMatch: 'full', canActivate: [AuthGuard]},
  {path: 'login', component: LoginComponent},
  {path: 'logout', component: LogoutComponent, canActivate: [AuthGuard]},

  {path: 'usuario', loadChildren: './entidades/usuario/usuario.module#UsuarioModule'},

  {path: 'reports/administracao', component: ReportScreenAdministracaoComponent, canActivate: [AuthGuard]},
  {path: 'reports/auxiliar', component: ReportScreenAuxiliarComponent, canActivate: [AuthGuard]},
  {path: 'reports/economico', component: ReportScreenEconomicoComponent, canActivate: [AuthGuard]},
  {path: 'reports/financeiro', component: ReportScreenFinanceiroComponent, canActivate: [AuthGuard]},
  {path: 'reports/procuradoria', component: ReportScreenProcuradoriaComponent, canActivate: [AuthGuard]},
  {path: 'reports/notafiscal', component: ReportScreenNotafiscalComponent, canActivate: [AuthGuard]},
  {path: 'reports/transporte', component: ReportScreenTransporteComponent, canActivate: [AuthGuard]},
  {path: 'reports/tributacao', component: ReportScreenTributacaoComponent, canActivate: [AuthGuard]},
  {path: 'reports/urbanismo', component: ReportScreenUrbanismoComponent, canActivate: [AuthGuard]},

  {path: 'agencia', loadChildren: './entidades/agencia/agencia.module#AgenciaModule'},
  {path: 'campanha', loadChildren: './entidades/campanha/campanha.module#CampanhaModule'},
  {path: 'cliente', loadChildren: './entidades/cliente/cliente.module#ClienteModule'},
  {path: 'faturamentopadrao', loadChildren: './entidades/faturamentopadrao/faturamentopadrao.module#FaturamentoPadraoModule'},
  {path: 'formato', loadChildren: './entidades/formato/formato.module#FormatoModule'},
  {path: 'formatorevista', loadChildren: './entidades/formatorevista/formatorevista.module#FormatoRevistaModule'},
  {path: 'mailpi', loadChildren: './entidades/mailpi/mailpi.module#MailPiModule'},
  {path: 'material', loadChildren: './entidades/material/material.module#MaterialModule'},
  {path: 'pais', loadChildren: './entidades/pais/pais.module#PaisModule'},
  {path: 'peca', loadChildren: './entidades/peca/peca.module#PecaModule'},
  {path: 'pedidoinsercao', loadChildren: './entidades/pedidoinsercao/pedidoinsercao.module#PedidoInsercaoModule'},
  {path: 'pedidoinsercaoitem', loadChildren: './entidades/pedidoinsercaoitem/pedidoinsercaoitem.module#PedidoInsercaoItemModule'},
  {path: 'planomidia', loadChildren: './entidades/planomidia/planomidia.module#PlanoMidiaModule'},
  {path: 'planomidiainsersao', loadChildren: './entidades/planomidiainsersao/planomidiainsersao.module#PlanoMidiaInsersaoModule'},
  {path: 'planomidiainsersaoitem', loadChildren: './entidades/planomidiainsersaoitem/planomidiainsersaoitem.module#PlanoMidiaInsersaoItemModule'},
  {path: 'produto', loadChildren: './entidades/produto/produto.module#ProdutoModule'},
  {path: 'programa', loadChildren: './entidades/programa/programa.module#ProgramaModule'},
  {path: 'tipomidia', loadChildren: './entidades/tipomidia/tipomidia.module#TipoMidiaModule'},
  {path: 'tipomidiadigital', loadChildren: './entidades/tipomidiadigital/tipomidiadigital.module#TipoMidiaDigitalModule'},
  {path: 'tipoproduto', loadChildren: './entidades/tipoproduto/tipoproduto.module#TipoProdutoModule'},
  {path: 'uf', loadChildren: './entidades/uf/uf.module#UfModule'},
  {path: 'veiculo', loadChildren: './entidades/veiculo/veiculo.module#VeiculoModule'},
  {path: 'vencimentopadrao', loadChildren: './entidades/vencimentopadrao/vencimentopadrao.module#VencimentoPadraoModule'},


  /*{path: 'alvaraemitido', loadChildren: './tributos/alvaraemitido/alvaraemitido.module#AlvaraEmitidoModule'},
  {path: 'alvarameioambiente', loadChildren: './tributos/alvarameioambiente/alvarameioambiente.module#AlvaraMeioAmbienteModule'},
  {path: 'alvaramotivostatus', loadChildren: './tributos/alvaramotivostatus/alvaramotivostatus.module#AlvaraMotivoStatusModule'},
  {path: 'alvaravigilanciasanitaria', loadChildren: './tributos/alvaravigilanciasanitaria/alvaravigilanciasanitaria.module#AlvaraVigilanciaSanitariaModule'},
  {path: 'bairro', loadChildren: './tributos/bairro/bairro.module#BairroModule'},
  {path: 'baixa', loadChildren: './tributos/baixa/baixa.module#BaixaModule'},
  {path: 'baixastatus', loadChildren: './tributos/baixastatus/baixastatus.module#BaixaStatusModule'},
  {path: 'banco', loadChildren: './tributos/banco/banco.module#BancoModule'},
  {path: 'bancocontrato', loadChildren: './tributos/bancocontrato/bancocontrato.module#BancoContratoModule'},
  {path: 'bcigrupo', loadChildren: './tributos/bcigrupo/bcigrupo.module#BciGrupoModule'},
  {path: 'bciitem', loadChildren: './tributos/bciitem/bciitem.module#BciItemModule'},
  {path: 'bcimodulo', loadChildren: './tributos/bcimodulo/bcimodulo.module#BciModuloModule'},
  {path: 'calendariofiscal', loadChildren: './tributos/calendariofiscal/calendariofiscal.module#CalendarioFiscalModule'},
  {path: 'cartorio', loadChildren: './tributos/cartorio/cartorio.module#CartorioModule'},
  {path: 'categoriaveiculo', loadChildren: './tributos/categoriaveiculo/categoriaveiculo.module#CategoriaVeiculoModule'},
  {path: 'certidaoemitida', loadChildren: './tributos/certidaoemitida/certidaoemitida.module#CertidaoEmitidaModule'},
  {path: 'certidaomotivostatus', loadChildren: './tributos/certidaomotivostatus/certidaomotivostatus.module#CertidaoMotivoStatusModule'},
  {path: 'cidade', loadChildren: './tributos/cidade/cidade.module#CidadeModule'},
  {path: 'cnae', loadChildren: './tributos/cnae/cnae.module#CnaeModule'},
  {path: 'cnaeclasse', loadChildren: './tributos/cnaeclasse/cnaeclasse.module#CnaeClasseModule'},
  {path: 'cnaedivisao', loadChildren: './tributos/cnaedivisao/cnaedivisao.module#CnaeDivisaoModule'},
  {path: 'cnaegrupo', loadChildren: './tributos/cnaegrupo/cnaegrupo.module#CnaeGrupoModule'},
  {path: 'cnaesecao', loadChildren: './tributos/cnaesecao/cnaesecao.module#CnaeSecaoModule'},
  {path: 'cnaesecundarios', loadChildren: './tributos/cnaesecundarios/cnaesecundarios.module#CnaeSecundariosModule'},
  {path: 'cnaeservico', loadChildren: './tributos/cnaeservico/cnaeservico.module#CnaeServicoModule'},
  {path: 'cobrancabancariastatus', loadChildren: './tributos/cobrancabancariastatus/cobrancabancariastatus.module#CobrancaBancariaStatusModule'},
  {path: 'concessao', loadChildren: './tributos/concessao/concessao.module#ConcessaoModule'},
  {path: 'concessaobox', loadChildren: './tributos/concessaobox/concessaobox.module#ConcessaoBoxModule'},
  {path: 'concessaotransporte', loadChildren: './tributos/concessaotransporte/concessaotransporte.module#ConcessaoTransporteModule'},
  {path: 'condominio', loadChildren: './tributos/condominio/condominio.module#CondominioModule'},
  {path: 'contabancaria', loadChildren: './tributos/contabancaria/contabancaria.module#ContaBancariaModule'},
  {path: 'contribuinte', loadChildren: './tributos/contribuinte/contribuinte.module#ContribuinteModule'},
  {path: 'creditobancario', loadChildren: './tributos/creditobancario/creditobancario.module#CreditoBancarioModule'},
  {path: 'creditobancarioitem', loadChildren: './tributos/creditobancarioitem/creditobancarioitem.module#CreditoBancarioItemModule'},
  {path: 'creditobancariostatus', loadChildren: './tributos/creditobancariostatus/creditobancariostatus.module#CreditoBancarioStatusModule'},
  {path: 'debito', loadChildren: './tributos/debito/debito.module#DebitoModule'},
  {path: 'debitoparcela', loadChildren: './tributos/debitoparcela/debitoparcela.module#DebitoParcelaModule'},
  {path: 'declaracaofiscal', loadChildren: './tributos/declaracaofiscal/declaracaofiscal.module#DeclaracaoFiscalModule'},
  {path: 'departamento', loadChildren: './tributos/departamento/departamento.module#DepartamentoModule'},
  {path: 'distrito', loadChildren: './tributos/distrito/distrito.module#DistritoModule'},
  {path: 'dividaativa', loadChildren: './tributos/dividaativa/dividaativa.module#DividaAtivaModule'},
  {path: 'dividaativaitem', loadChildren: './tributos/dividaativaitem/dividaativaitem.module#DividaAtivaItemModule'},
  {path: 'emissaocobranca', loadChildren: './tributos/emissaocobranca/emissaocobranca.module#EmissaoCobrancaModule'},
  {path: 'emissaocobrancaitem', loadChildren: './tributos/emissaocobrancaitem/emissaocobrancaitem.module#EmissaoCobrancaItemModule'},
  {path: 'empresa', loadChildren: './tributos/empresa/empresa.module#EmpresaModule'},
  {path: 'empresaservico', loadChildren: './tributos/empresaservico/empresaservico.module#EmpresaServicoModule'},
  {path: 'engenheiro', loadChildren: './tributos/engenheiro/engenheiro.module#EngenheiroModule'},
  {path: 'enquadramentofiscal', loadChildren: './tributos/enquadramentofiscal/enquadramentofiscal.module#EnquadramentoFiscalModule'},
  {path: 'entidade', loadChildren: './tributos/entidade/entidade.module#EntidadeModule'},
  {path: 'fundamentacaolegal', loadChildren: './tributos/fundamentacaolegal/fundamentacaolegal.module#FundamentacaoLegalModule'},
  {path: 'habitese', loadChildren: './tributos/habitese/habitese.module#HabiteseModule'},
  {path: 'historicosimplesnacional', loadChildren: './tributos/historicosimplesnacional/historicosimplesnacional.module#HistoricoSimplesNacionalModule'},
  {path: 'imovel', loadChildren: './tributos/imovel/imovel.module#ImovelModule'},
  {path: 'inscricaostatus', loadChildren: './tributos/inscricaostatus/inscricaostatus.module#InscricaoStatusModule'},
  {path: 'iptu', loadChildren: './tributos/iptu/iptu.module#IptuModule'},
  {path: 'iss', loadChildren: './tributos/iss/iss.module#IssModule'},
  {path: 'itiv', loadChildren: './tributos/itiv/itiv.module#ItivModule'},
  {path: 'localconcessaobox', loadChildren: './tributos/localconcessaobox/localconcessaobox.module#LocalConcessaoBoxModule'},
  {path: 'logradouro', loadChildren: './tributos/logradouro/logradouro.module#LogradouroModule'},
  {path: 'logradourosegmento', loadChildren: './tributos/logradourosegmento/logradourosegmento.module#LogradouroSegmentoModule'},
  {path: 'loteamento', loadChildren: './tributos/loteamento/loteamento.module#LoteamentoModule'},
  {path: 'moduloservicotomado', loadChildren: './tributos/moduloservicotomado/moduloservicotomado.module#ModuloServicoTomadoModule'},
  {path: 'moduloservicotomadodebito', loadChildren: './tributos/moduloservicotomadodebito/moduloservicotomadodebito.module#ModuloServicoTomadoDebitoModule'},
  {path: 'moeda', loadChildren: './tributos/moeda/moeda.module#MoedaModule'},
  {path: 'moedacotacao', loadChildren: './tributos/moedacotacao/moedacotacao.module#MoedaCotacaoModule'},
  {path: 'motivostatus', loadChildren: './tributos/motivostatus/motivostatus.module#MotivoStatusModule'},
  {path: 'naturezajuridica', loadChildren: './tributos/naturezajuridica/naturezajuridica.module#NaturezaJuridicaModule'},
  {path: 'naturezaoperacaoempresa', loadChildren: './tributos/naturezaoperacaoempresa/naturezaoperacaoempresa.module#NaturezaOperacaoEmpresaModule'},
  {path: 'naturezatributacao', loadChildren: './tributos/naturezatributacao/naturezatributacao.module#NaturezaTributacaoModule'},
  {path: 'notafiscalavulsa', loadChildren: './tributos/notafiscalavulsa/notafiscalavulsa.module#NotaFiscalAvulsaModule'},
  {path: 'notafiscaleletronica', loadChildren: './tributos/notafiscaleletronica/notafiscaleletronica.module#NotaFiscalEletronicaModule'},
  {path: 'operador', loadChildren: './tributos/operador/operador.module#OperadorModule'},
  {path: 'operadorempresa', loadChildren: './tributos/operadorempresa/operadorempresa.module#OperadorEmpresaModule'},
  {path: 'operadorrecurso', loadChildren: './tributos/operadorrecurso/operadorrecurso.module#OperadorRecursoModule'},
  {path: 'orgaoregistroempresa', loadChildren: './tributos/orgaoregistroempresa/orgaoregistroempresa.module#OrgaoRegistroEmpresaModule'},
  {path: 'padraoconstrutivo', loadChildren: './tributos/padraoconstrutivo/padraoconstrutivo.module#PadraoConstrutivoModule'},
  {path: 'pais', loadChildren: './tributos/pais/pais.module#PaisModule'},
  {path: 'parcelamentotributario', loadChildren: './tributos/parcelamentotributario/parcelamentotributario.module#ParcelamentoTributarioModule'},
  {path: 'parcelamentotributariodebito', loadChildren: './tributos/parcelamentotributariodebito/parcelamentotributariodebito.module#ParcelamentoTributarioDebitoModule'},
  {path: 'parcelamentotributarioitem', loadChildren: './tributos/parcelamentotributarioitem/parcelamentotributarioitem.module#ParcelamentoTributarioItemModule'},
  {path: 'porteempresa', loadChildren: './tributos/porteempresa/porteempresa.module#PorteEmpresaModule'},
  {path: 'precopublico', loadChildren: './tributos/precopublico/precopublico.module#PrecoPublicoModule'},
  {path: 'processoexecucao', loadChildren: './tributos/processoexecucao/processoexecucao.module#ProcessoExecucaoModule'},
  {path: 'processoexecucaohistorico', loadChildren: './tributos/processoexecucaohistorico/processoexecucaohistorico.module#ProcessoExecucaoHistoricoModule'},
  {path: 'processoexecucaoitem', loadChildren: './tributos/processoexecucaoitem/processoexecucaoitem.module#ProcessoExecucaoItemModule'},
  {path: 'processoexecucaostatus', loadChildren: './tributos/processoexecucaostatus/processoexecucaostatus.module#ProcessoExecucaoStatusModule'},
  {path: 'procurador', loadChildren: './tributos/procurador/procurador.module#ProcuradorModule'},
  {path: 'ramoatividade', loadChildren: './tributos/ramoatividade/ramoatividade.module#RamoAtividadeModule'},
  {path: 'receita', loadChildren: './tributos/receita/receita.module#ReceitaModule'},
  {path: 'recursosistema', loadChildren: './tributos/recursosistema/recursosistema.module#RecursoSistemaModule'},
  {path: 'responsavellegal', loadChildren: './tributos/responsavellegal/responsavellegal.module#ResponsavelLegalModule'},
  {path: 'servico', loadChildren: './tributos/servico/servico.module#ServicoModule'},
  {path: 'servicogrupo', loadChildren: './tributos/servicogrupo/servicogrupo.module#ServicoGrupoModule'},
  {path: 'servicotomado', loadChildren: './tributos/servicotomado/servicotomado.module#ServicoTomadoModule'},
  {path: 'setor', loadChildren: './tributos/setor/setor.module#SetorModule'},
  {path: 'simplesnacional', loadChildren: './tributos/simplesnacional/simplesnacional.module#SimplesNacionalModule'},
  {path: 'socio', loadChildren: './tributos/socio/socio.module#SocioModule'},
  {path: 'statusdebito', loadChildren: './tributos/statusdebito/statusdebito.module#StatusDebitoModule'},
  {path: 'statusdeclaracaoeletronica', loadChildren: './tributos/statusdeclaracaoeletronica/statusdeclaracaoeletronica.module#StatusDeclaracaoEletronicaModule'},
  {path: 'statusnotafiscal', loadChildren: './tributos/statusnotafiscal/statusnotafiscal.module#StatusNotaFiscalModule'},
  {path: 'statussimplesnacional', loadChildren: './tributos/statussimplesnacional/statussimplesnacional.module#StatusSimplesNacionalModule'},
  {path: 'su', loadChildren: './tributos/su/su.module#SuModule'},
  {path: 'tff', loadChildren: './tributos/tff/tff.module#TffModule'},
  {path: 'tipoalvara', loadChildren: './tributos/tipoalvara/tipoalvara.module#TipoAlvaraModule'},
  {path: 'tipobaixa', loadChildren: './tributos/tipobaixa/tipobaixa.module#TipoBaixaModule'},
  {path: 'tipobancocontrato', loadChildren: './tributos/tipobancocontrato/tipobancocontrato.module#TipoBancoContratoModule'},
  {path: 'tipocartorio', loadChildren: './tributos/tipocartorio/tipocartorio.module#TipoCartorioModule'},
  {path: 'tipocertidao', loadChildren: './tributos/tipocertidao/tipocertidao.module#TipoCertidaoModule'},
  {path: 'tipoconcessao', loadChildren: './tributos/tipoconcessao/tipoconcessao.module#TipoConcessaoModule'},
  {path: 'tipoconstituicaoempresa', loadChildren: './tributos/tipoconstituicaoempresa/tipoconstituicaoempresa.module#TipoConstituicaoEmpresaModule'},
  {path: 'tipocontribuinte', loadChildren: './tributos/tipocontribuinte/tipocontribuinte.module#TipoContribuinteModule'},
  {path: 'tipodebito', loadChildren: './tributos/tipodebito/tipodebito.module#TipoDebitoModule'},
  {path: 'tipodeclaracao', loadChildren: './tributos/tipodeclaracao/tipodeclaracao.module#TipoDeclaracaoModule'},
  {path: 'tipodeclarante', loadChildren: './tributos/tipodeclarante/tipodeclarante.module#TipoDeclaranteModule'},
  {path: 'tipodividaativa', loadChildren: './tributos/tipodividaativa/tipodividaativa.module#TipoDividaAtivaModule'},
  {path: 'tipodocumentofiscal', loadChildren: './tributos/tipodocumentofiscal/tipodocumentofiscal.module#TipoDocumentoFiscalModule'},
  {path: 'tipoimovel', loadChildren: './tributos/tipoimovel/tipoimovel.module#TipoImovelModule'},
  {path: 'tipologradouro', loadChildren: './tributos/tipologradouro/tipologradouro.module#TipoLogradouroModule'},
  {path: 'tipooperador', loadChildren: './tributos/tipooperador/tipooperador.module#TipoOperadorModule'},
  {path: 'tipoparcelamentotributario', loadChildren: './tributos/tipoparcelamentotributario/tipoparcelamentotributario.module#TipoParcelamentoTributarioModule'},
  {path: 'tipounidade', loadChildren: './tributos/tipounidade/tipounidade.module#TipoUnidadeModule'},
  {path: 'tipounidadeempresa', loadChildren: './tributos/tipounidadeempresa/tipounidadeempresa.module#TipoUnidadeEmpresaModule'},
  {path: 'tipousoalvara', loadChildren: './tributos/tipousoalvara/tipousoalvara.module#TipoUsoAlvaraModule'},
  {path: 'tipoveiculo', loadChildren: './tributos/tipoveiculo/tipoveiculo.module#TipoVeiculoModule'},
  {path: 'tributo', loadChildren: './tributos/tributo/tributo.module#TributoModule'},
  {path: 'txmercado', loadChildren: './tributos/txmercado/txmercado.module#TxMercadoModule'},
  {path: 'uf', loadChildren: './tributos/uf/uf.module#UfModule'},
  {path: 'unidadegestora', loadChildren: './tributos/unidadegestora/unidadegestora.module#UnidadeGestoraModule'},
  {path: 'veiculo', loadChildren: './tributos/veiculo/veiculo.module#VeiculoModule'},
  {path: 'vupconstrucao', loadChildren: './tributos/vupconstrucao/vupconstrucao.module#VupConstrucaoModule'},
  {path: 'vupterreno', loadChildren: './tributos/vupterreno/vupterreno.module#VupTerrenoModule'},
  {path: 'zona', loadChildren: './tributos/zona/zona.module#ZonaModule'}*/
];
@NgModule({  exports: [RouterModule],  imports: [RouterModule.forRoot(routes)]})export class AppRoutingModule {}
